/* อัตราค่าธรรมเนียมการศึกษา ปีงบประมาณ 2568 — จากแท็บ "ค่าธรรมเนียม68"
   สร้างอัตโนมัติจาก apps/web/scripts/import-fee-sheet.mjs (อย่าแก้ไฟล์นี้ด้วยมือ)
   https://docs.google.com/spreadsheets/d/1ECcfx9i7Eua_YaoQcdbLaXwsXaEZ01AS80PDOMZKvDQ */

import type { FeeRow } from './feeData';

export const FEE_RATES: FeeRow[] = [
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'พ.บ. แพทยศาสตรบัณฑิต (หลักสูตร 6 ปี)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'พทป.บ. การแพทย์แผนไทยประยุกต์บัณฑิต',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 20000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ฉุกเฉินการแพทย์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 22000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเภสัชศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ภ.บ. การบริบาลทางเภสัชกรรม',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 32500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะพยาบาลศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'พย.บ. พยาบาลศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 39500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ส.บ. สาธารณสุขศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 16000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. โภชนาการและการกำหนดอาหาร',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 16000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. อนามัยสิ่งแวดล้อม',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 16000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. อาชีวอนามัยและความปลอดภัย',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 16000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เคมี',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ชีววิทยา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ฟิสิกส์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ฟิสิกส์ประยุกต์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. คณิตศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. สถิติ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. จุลชีววิทยา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. พันธุศาสตร์โมเลกุล',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. นวัตกรรมทางชีวเคมี',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. ฟิสิกส์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. พลังงานและการควบคุมระบบอัตโนมัติ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ฟิสิกส์ และ วท.ม ฟิสิกส์ (หลักสูตร 2 ปริญญา)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: null,
    rateText: 'ปี 1-3 = 15,000 , ปี 4-5 = 20,000',
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ฟิสิกส์ และ กศ.ม. หลักสูตรและการสอน (หลักสูตร 2 ปริญญา)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: null,
    rateText: 'ปีที่ 1 - ปีที่ 3 จำนวน 15,000 ,ปีที่ 4 - ปีที่ 5 จำนวน 23,000',
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เทคโนโลยีการอาหารและโภชนาการ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เทคโนโลยีชีวภาพและอุตสาหกรรมชีวภาพ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เกษตรศาสตร์ (วิชาเอกพืชสวน)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เกษตรศาสตร์ (วิชาเอกพืชไร่)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. พัฒนาผลิตภัณฑ์อาหาร',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. สัตวศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ประมง',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'สพ.บ. สัตวแพทยศาสตร์ (หลักสูตร 6 ปี)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 38000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. การพยาบาลสัตว์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เทคนิคการสัตวแพทย์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เทคโนโลยีสิ่งแวดล้อม',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. การจัดการทรัพยากรธรรมชาติและสิ่งแวดล้อม',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. สิ่งแวดล้อมศึกษาและเกษตรศึกษา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'สท.บ. สารสนเทศศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เทคโนโลยีสารสนเทศ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. วิทยาการคอมพิวเตอร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. สื่อนฤมิต',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'นศ.บ. นิเทศศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. เทคโนโลยีนวัตกรรมสำหรับธุรกิจสมัยใหม่',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. วิทยาการข้อมูลและวิศวกรรมข้อมูล',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ภูมิสารสนเทศศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. วิทยาการคอมพิวเตอร์และเทคโนโลยี (หลักสูตรนานาชาติ)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 35000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมโยธา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมเครื่องกล',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมชีวภาพและอาหาร',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมสิ่งแวดล้อม',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมเมคาทรอนิกส์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมไฟฟ้า',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมรถไฟความร็วสูง',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วศ.บ. วิศวกรรมยานยนต์ไฟฟ้า',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 17500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'สถ.บ. สถาปัตยกรรม (หลักสูตร 5 ปี)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'สถ.บ. สถาปัตยกรรมผังเมือง (หลักสูตร 5 ปี)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'สถ.บ. สถาปัตยกรรมภายใน (หลักสูตร 5 ปี)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'ศป.บ. นวัตกรรมการออกแบบ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'ภ.สถ.บ. ภูมิสถาปัตยกรรม (หลักสูตร 5 ปี)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'ศป.บ. นวัตกรรมการออกแบบ และ กศ.ม. เทคโนโลยีสื่อสารการศึกษา (หลักสูตร 2 ปริญญา)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: null,
    rateText: 'ปีที่ 1 - ปีที่ 3 จำนวน 18,000 ,ปีที่ 4 - ปีที่ 5 จำนวน 31,000',
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บช.บ. บัญชีบัณฑิต',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บธ.บ. การตลาด',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บธ.บ. การจัดการสมัยใหม่',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บธ.บ. คอมพิวเตอร์ธุรกิจ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บธ.บ. ธุรกิจระหว่างประเทศ (หลักสูตรนานาชาติ)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 45000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บธ.บ. การบริหารการเงิน',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บธ.บ. ธุรกิจดิจิทัลและระบบสารสนเทศ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'ศ.บ. เศรษฐศาสตร์ธุรกิจ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาตรี',
    prog: 'บธ.บ. การเป็นผู้ประกอบการธุรกิจสมัยใหม่',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการท่องเที่ยวและการโรงแรม',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. การจัดการการท่องเที่ยวและบริการ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการท่องเที่ยวและการโรงแรม',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. การจัดการโรงแรมและบริการ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการท่องเที่ยวและการโรงแรม',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. การจัดการการท่องเที่ยวและบริการนานาชาติ (หลักสูตรภาษาอังกฤษ)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 35000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการท่องเที่ยวและการโรงแรม',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ศิลปะการปรุงอาหารและการจัดการบริการด้วยไมตรีจิต',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาไทย',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. การสร้างสรรค์คอนเทนต์และนวัตกรรมสื่อดิจิทัล',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาอังกฤษ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาอังกฤษเพื่อการสื่อสารนานาชาติ (หลักสูตรนานาชาติ)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาอังกฤษธุรกิจ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาจีน',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาตะวันออก (ภาษาญี่ปุ่น)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาฝรั่งเศส',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ประวัติศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. การพัฒนาชุมชนและสังคม',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาตะวันออก (ภาษาเกาหลี)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาและวัฒนธรรมอาเซียน (เขมร)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาและวัฒนธรรมอาเซียน (ลาว)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. ภาษาและวัฒนธรรมอาเซียน (เวียดนาม)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. ภูมิศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาตรี',
    prog: 'ร.บ. การเมืองการปกครอง',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาตรี',
    prog: 'ร.บ. รัฐประศาสนศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาตรี',
    prog: 'ร.บ. ความสัมพันธ์ระหว่างประเทศ',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาตรี',
    prog: 'ร.บ. การเมืองการปกครอง และ ร.ม. รัฐศาสตร์ (หลักสูตร 2 ปริญญา)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: null,
    rateText: 'ปี 1-3 = 13,000 , ปี 4-5 = 28,200',
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาตรี',
    prog: 'ร.บ. รัฐประศาสนศาสตร์ และ ร.ม. รัฐศาสตร์ (หลักสูตร 2 ปริญญา)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: null,
    rateText: 'ปี 1-3 = 13,000 , ปี 4-5 = 28,200',
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาตรี',
    prog: 'ร.บ. ความสัมพันธ์ระหว่างประเทศ และ ร.ม. รัฐศาสตร์ (หลักสูตร 2 ปริญญา)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: null,
    rateText: 'ปี 1-3 = 13,000 , ปี 4-5 = 28,200',
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. การศึกษา (วิทยาศาสตร์ทั่วไป)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. คณิตศาสตร์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. การศึกษา (สังคมศึกษา)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. การศึกษา (ภาษาอังกฤษ)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. การศึกษา (ภาษาไทย)',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. การศึกษาปฐมวัย',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. เทคโนโลยีการศึกษาและคอมพิวเตอร์ศึกษา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. จิตวิทยา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'วท.บ. วิทยาศาสตร์การกีฬา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. พลศึกษาและการกีฬา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศป.บ. ทัศนศิลป์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศป.บ. ศิลปะการแสดง',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศป.บ. การออกแบบและพัฒนาผลิตภัณฑ์',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'ศศ.บ. การจัดการวัฒนธรรม',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยดุริยางคศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'ดศ.บ. ดุริยางคศาสตรบัณฑิต',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยดุริยางคศิลป์',
    lvl: 'ปริญญาตรี',
    prog: 'กศ.บ. ดนตรีศึกษา',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 16000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะนิติศาสตร์',
    lvl: 'ปริญญาตรี',
    prog: 'น.บ. นิติศาสตรบัณฑิต',
    plan: null,
    mode: 'ในเวลา',
    sems: null,
    rate: 15000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศศ.ม. ภาษาไทย',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 31250,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. การสอนภาษาอังกฤษ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 31250,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศศ.ม. สังคมศึกษา ศาสนา และวัฒนธรรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 29000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. การสอนภาษาและวรรณกรรมไทย',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 31250,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศศ.ม. ภาษาอังกฤษและการสื่อสารระหว่างวัฒนธรรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 31250,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. เทคโนโลยีและสื่อสารการศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 29500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. การศึกษาปฐมวัย',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 38000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. การบริหารและพัฒนาการศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. การสอนวิทยาศาสตร์และคณิตศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 26000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. หลักสูตรและการสอน',
    plan: 'แผน 1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. หลักสูตรและการสอน',
    plan: 'แผน 2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. จิตวิทยา',
    plan: 'แขนงจิตวิทยาการศึกษาและจิตวิทยาสุขภาพ',
    mode: 'นอกเวลา',
    sems: null,
    rate: 42500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. จิตวิทยา',
    plan: 'แขนงจิตวิทยาการปรึกษา',
    mode: 'นอกเวลา',
    sems: null,
    rate: 42500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. วิทยาศาสตร์การออกกำลังกายและการกีฬา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 26000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. วิจัยและประเมินผลการศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 24200,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ประกาศนียบัตรบัณฑิตชั้นสูง สาขาวิชาการศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'บัญชีมหาบัณฑิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 48000,
    rateText: null,
    rateIntl: 100000,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'บธ.ม. การตลาดระหว่างประเทศและนวัตกรรมผู้ประกอบการ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 27000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'บธ.ม. การจัดการเชิงกลยุทธ์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 27000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'ศ.ม. เศรษฐศาสตร์ธุรกิจและนวัตกรรมทางธุรกิจ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 27000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'กจ.ม. การจัดการสมัยใหม่',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 27000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'บธ.ม. ธุรกิจดิจิทัลและระบบสารสนเทศ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 27000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'บธ.ม. บริหารธุรกิจและนวัตกรรมดิจิทัล',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. การจัดการเมืองอัจฉริยะและนวัตกรรมดิจิทัล',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 27000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'บธ.ม. ธุรกิจดนตรี ศิลปะและวัฒนธรรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาโท',
    prog: 'บธ.ม. การบัญชีดิจิทัลและปัญญาประดิษฐ์ประยุกต์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศศ.ม. การวิจัยและสร้างสรรค์ศิลปกรรมศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30800,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศป.ม. ทัศนศิลป์',
    plan: 'แผน ก แบบ ก1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 60000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศป.ม. ทัศนศิลป์',
    plan: 'แผน ก แบบ ก2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 45000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศศ.ม. วัฒนธรรมศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 22800,
    rateText: null,
    rateIntl: 55000,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ศป.ม. ศิลปะการแสดง',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 48000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการท่องเที่ยวและการโรงแรม',
    lvl: 'ปริญญาโท',
    prog: 'ศศ.ม. การจัดการการท่องเที่ยวและการโรงแรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 39600,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาโท',
    prog: 'รัฐศาสตรมหาบัณฑิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 23000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยดุริยางคศิลป์',
    lvl: 'ปริญญาโท',
    prog: 'ดุริยางคศาสตรมหาบัณฑิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 35700,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยดุริยางคศิลป์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. ดนตรีศึกษา',
    plan: 'แผน ก แบบ ก2(1)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 35700,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยดุริยางคศิลป์',
    lvl: 'ปริญญาโท',
    prog: 'กศ.ม. ดนตรีศึกษา',
    plan: 'แผน ก แบบ ก2(2)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 43700,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เคมี',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. ชีววิทยา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 20000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. ฟิสิกส์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. คณิตศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. คณิตศาสตรศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. สหวิทยาการจัดการสถิติ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. พลังงาน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เทคโนโลยีการอาหาร',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 39100,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เทคโนโลยีชีวภาพและธุรกิจชีวภาพ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 22000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เกษตรศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 18300,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. นวัตกรรมและเทคโนโลยีผู้ประกอบการ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วศ.ม. วิศวกรรมเครื่องกล',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วศ.ม. วิศวกรรมโยธา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วศ.ม. วิศวกรรมไฟฟ้าและคอมพิวเตอร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาโท',
    prog: 'สถ.ม. การวางผังเมืองและชุมชนอัจฉริยะ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาโท',
    prog: 'สถ.ม. สหวิทยาการออกแบบสิ่งแวดล้อมสรรค์สร้าง',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 55000,
    rateText: null,
    rateIntl: 110000,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. การจัดการสิ่งแวดล้อมอย่างยั่งยืน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 28000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. สิ่งแวดล้อมศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 20000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เทคโนโลยีสิ่งแวดล้อมและนวัตกรรมเพื่อความยั่งยืน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 28000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. วิทยาการคอมพิวเตอร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 48600,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เทคโนโลยีสารสนเทศ',
    plan: 'แผน 1 แบบ ก(1)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 27000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เทคโนโลยีสารสนเทศ',
    plan: 'แผน 1 แบบ ก(2) แผน 2 (ข)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 34000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. สื่อนฤมิต',
    plan: 'แผน ก แบบ ก1 แบบ ก 2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. สื่อนฤมิต',
    plan: 'แผน ข',
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาโท',
    prog: 'สท.ม. สารสนเทศศาสตร์และนวัตกรรมดิจิทัล',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาโท',
    prog: 'นศ.ม. นิเทศศาสตร์สร้างสรรค์ดิจิทัล',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: 82500,
    note: null,
  },
  {
    fac: 'สถาบันวิจัยวลัยรุกขเวช',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. ความหลากหลายทางชีวภาพ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 18000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะพยาบาลศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'พย.ม. การพยาบาลจิตเวชและสุขภาพจิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 42500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะพยาบาลศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'พย.ม. การพยาบาลผู้ใหญ่และผู้สูงอายุ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 42500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะพยาบาลศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'พย.ม. การผดุงครรภ์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 42500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเภสัชศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. สมุนไพรและการแพทย์แผนไทย',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 29600,
    rateText: null,
    rateIntl: 66000,
    note: null,
  },
  {
    fac: 'คณะเภสัชศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'ภ.ม. เภสัชกรรมคลินิก',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 37000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'สาธารณสุขศาสตรมหาบัณฑิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 23000,
    rateText: null,
    rateIntl: 55000,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เทคโนโลยีทางสุขภาพและความปลอดภัย',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 28000,
    rateText: null,
    rateIntl: 66000,
    note: null,
  },
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เวชศาสตร์ชุมชน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. นวัตกรรมสุขภาพเขตร้อน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'การแพทย์แผนไทยประยุกต์มหาบัณฑิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 35000,
    rateText: null,
    rateIntl: 82500,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. เวชศาสตร์ชุมชน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. นวัตกรรมสุขภาพเขตร้อน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 25000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'การแพทย์แผนไทยประยุกต์มหาบัณฑิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 35000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'วท.ม. นวัตกรรมวิทยาศาสตร์การสัตวแพทย์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 32000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะนิติศาสตร์',
    lvl: 'ปริญญาโท',
    prog: 'น.ม. นิตินวัตกรรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ภาษาไทย',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 55000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. สังคมศึกษา ศาสนา และวัฒนธรรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะมนุษยศาสตร์และสังคมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การสอนภาษาอังกฤษ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 65000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. จิตวิทยา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 51900,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิจัยและประเมินผลการศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. หลักสูตรและการสอน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เทคโนโลยีและสื่อสารการศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิทยาศาสตร์การออกกำลังกายและการกีฬา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 56540,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศึกษาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'กศ.ด. การบริหารและพัฒนาการศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 70000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การจัดการเมืองอัจฉริยะและนวัตกรรมดิจิทัล',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การตลาดระหว่างประเทศและนวัตกรรมผู้ประกอบการ',
    plan: 'แบบ 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การตลาดระหว่างประเทศและนวัตกรรมผู้ประกอบการ',
    plan: 'แบบ 2.2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การบัญชี',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. บริหารธุรกิจและนวัตกรรมดิจิทัล',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ธุรกิจดิจิทัลและระบบสารสนเทศ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ธุรกิจดนตรี ศิลปะและวัฒนธรรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 60000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการบัญชีและการจัดการ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การบัญชีดิจิทัลและปัญญาประดิษฐ์ประยุกต์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การวิจัยและสร้างสรรค์ศิลปกรรมศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 59400,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วัฒนธรรมศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 52000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ทัศนศิลป์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 59000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะศิลปกรรมศาสตร์และวัฒนธรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ศิลปะการแสดง',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 59400,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะการท่องเที่ยวและการโรงแรม',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การจัดการการท่องเที่ยวและโรงแรม',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 58500,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยการเมืองการปกครอง',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. รัฐศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 65000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'วิทยาลัยดุริยางคศิลป์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ดุริยางคศิลป์',
    plan: 'แบบ 1.1, 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 57400,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'วิทยาลัยดุริยางคศิลป์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ดุริยางคศิลป์',
    plan: 'แบบ 2.2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 60000,
    rateText: null,
    rateIntl: 75000,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เคมี',
    plan: 'แบบ 1.1, 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เคมี',
    plan: '2.2 ก้าวหน้า (4 ปีการศึกษา) (โทควบเอก)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เคมี',
    plan: '2.2 (5 ปีการศึกษา) (โทควบเอก)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. สหวิทยาการจัดการสถิติ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. บรรพชีวินวิทยา',
    plan: 'แบบ 1.1 และ 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ฟิสิกส์',
    plan: 'แบบ 1.2 และ 2.2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: 75000,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ฟิสิกส์',
    plan: 'แบบ 1.1 และ 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. นวัตกรรมวิทยาศาสตร์และธุรกิจ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิทยาศาสตร์ชีวภาพ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. นวัตกรรมเทคโนโลยีชีวภาพเพื่อธุรกิจ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 32000,
    rateText: null,
    rateIntl: 75000,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เกษตรศาสตร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 47000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะเทคโนโลยี',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. นวัตกรรมเกษตรและการแปรรูปผลิตภัณฑ์เกษตรเพื่อธุรกิจ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 35000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิศวกรรมเครื่องกล',
    plan: 'แบบ 1.1, 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิศวกรรมเครื่องกล',
    plan: 'แบบ 1.2, 2.2 (4 ปีการศึกษา)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: 75000,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิศวกรรมโยธา',
    plan: 'แบบ 1.1, 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิศวกรรมโยธา',
    plan: 'แบบ 1.2, 2.2 (4 ปีการศึกษา)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: 75000,
    note: null,
  },
  {
    fac: 'คณะวิศวกรรมศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิศวกรรมไฟฟ้าและคอมพิวเตอร์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาเอก',
    prog: 'สถ.ด. สหวิทยาการออกแบบสิ่งแวดล้อมสรรค์สร้าง',
    plan: 'แผน 1.1 และแผน 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 60000,
    rateText: null,
    rateIntl: 120000,
    note: null,
  },
  {
    fac: 'คณะสถาปัตยกรรมศาสตร์ ผังเมืองและนฤมิตศิลป์',
    lvl: 'ปริญญาเอก',
    prog: 'สถ.ด. สหวิทยาการออกแบบสิ่งแวดล้อมสรรค์สร้าง',
    plan: 'แผน 1.2 และแผน 2.2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 60000,
    rateText: null,
    rateIntl: 120000,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. สิ่งแวดล้อมศึกษา',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การจัดการสิ่งแวดล้อมอย่างยั่งยืน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะสิ่งแวดล้อมและทรัพยากรศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. นวัตกรรมเทคโนโลยีสิ่งแวดล้อมและการจัดการพลังงาน',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิทยาการคอมพิวเตอร์',
    plan: 'แบบ 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 55000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เทคโนโลยีสารสนเทศ',
    plan: 'แบบ 1.1, 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 55000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เทคโนโลยีสารสนเทศ',
    plan: 'แบบ 2.2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะวิทยาการสารสนเทศ',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. สื่อนฤมิต',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 40000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'สถาบันวิจัยวลัยรุกขเวช',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. ความหลากหลายทางชีวภาพ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 30000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'สาธารณสุขศาสตรดุษฎีบัณฑิต',
    plan: 'แบบ 1.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 66000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'สาธารณสุขศาสตรดุษฎีบัณฑิต',
    plan: 'แบบ 1.2 (4 ปีการศึกษา)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 62000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'สาธารณสุขศาสตรดุษฎีบัณฑิต',
    plan: 'แบบ 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 66000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'สาธารณสุขศาสตรดุษฎีบัณฑิต',
    plan: 'แบบ 2.2 (4 ปีการศึกษา)',
    mode: 'นอกเวลา',
    sems: null,
    rate: 62000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เทคโนโลยีทางสุขภาพและความปลอดภัย',
    plan: 'แบบ 1.1, 2.1',
    mode: 'นอกเวลา',
    sems: null,
    rate: 66000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะสาธารณสุขศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. เทคโนโลยีทางสุขภาพและความปลอดภัย',
    plan: 'แบบ 1.2, 2.2',
    mode: 'นอกเวลา',
    sems: null,
    rate: 56000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. วิทยาศาสตร์สุขภาพ',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: null,
    note: null,
  },
  {
    fac: 'คณะแพทยศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. การแพทย์แผนไทยประยุกต์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 60000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
  {
    fac: 'คณะสัตวแพทยศาสตร์',
    lvl: 'ปริญญาเอก',
    prog: 'ปร.ด. นวัตกรรมวิทยาศาสตร์การสัตวแพทย์',
    plan: null,
    mode: 'นอกเวลา',
    sems: null,
    rate: 50000,
    rateText: null,
    rateIntl: 80000,
    note: null,
  },
];
